// Code generated by openapi-rpc-codegen (go-server). DO NOT EDIT.

package {{ .Package }}

import (
	"context"
	"net/http"
	{{- if .HasQuery }}
	"strconv"
	{{- end }}

	"github.com/go-chi/chi/v5"
)

{{- /* Path structs + inline Body/Resp only when needed */}}

{{- range .Tags }}
{{- range .Routes }}

{{- if .HasPath }}
type {{ .PathType }} struct {
{{- range .PathFields }}
	{{ .Name }} {{ .Type }}
{{- end }}
}
{{- end }}

{{- if .HasQuery }}
type {{ .QueryType }} struct {
{{- range .QueryFields }}
	{{ .Name }} {{ .Type }} {{ .Tag }}
{{- end }}
}
{{- end }}

{{- if .HasBody }}
{{- if .BodyInline }}
type {{ .BodyType }} = any
{{- end }}
{{- end }}

{{- if .RespInline }}
type {{ .RespType }} = any
{{- end }}

{{- end }}
{{- end }}

{{- /* Service interfaces per Tag */}}

{{- range .Tags }}

type {{ .Name }}Service interface {
{{- range .Routes }}
	{{ goMethodName .Name }}(ctx context.Context{{ if .HasPath }}, path {{ .PathType }}{{ end }}{{ if .HasQuery }}, query *{{ .QueryType }}{{ end }}{{ if .HasBody }}, body {{ .BodyType }}{{ end }}) ({{ .RespType }}, error)
{{- end }}
}

{{- end }}

type Services struct {
{{- range .Tags }}
	{{ .Name }} {{ .Name }}Service
{{- end }}
}

func RegisterRoutes(r chi.Router, svc Services) {
{{- range .Tags }}
	if svc.{{ .Name }} == nil {
		panic("Services.{{ .Name }} is nil")
	}
{{- end }}

{{- range .Tags }}
{{- range .Routes }}
	r.{{ .MethodName }}({{ printf "%q" .Path }}, {{ .HandlerName }}(svc.{{ .TagName }}))
{{- end }}
{{- end }}
}

{{- /* Handlers */}}

{{- range .Tags }}
{{- range .Routes }}

func {{ .HandlerName }}(svc {{ .TagName }}Service) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		{{- if .HasPath }}
		var path {{ .PathType }}
		{{- range .PathFields }}
		path.{{ .Name }} = chi.URLParam(r, {{ printf "%q" .JSONName }})
		{{- end }}
		{{- end }}

		{{- if .HasQuery }}
		var query {{ .QueryType }}
		values := r.URL.Query()
		{{- range .QueryFields }}
		{{- if .Required }}
		value{{ .Name }} := values.Get({{ printf "%q" .JSONName }})
		if value{{ .Name }} == "" {
			WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "missing query param: {{ .JSONName }}"})
			return
		}
		{{- if eq .ParseKind "int64" }}
		if parsed{{ .Name }}, err := strconv.ParseInt(value{{ .Name }}, 10, 64); err != nil {
			WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid query param: {{ .JSONName }}"})
			return
		} else {
			{{- if .IsPointer }}
			query.{{ .Name }} = &parsed{{ .Name }}
			{{- else }}
			query.{{ .Name }} = parsed{{ .Name }}
			{{- end }}
		}
		{{- else if eq .ParseKind "float64" }}
		if parsed{{ .Name }}, err := strconv.ParseFloat(value{{ .Name }}, 64); err != nil {
			WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid query param: {{ .JSONName }}"})
			return
		} else {
			{{- if .IsPointer }}
			query.{{ .Name }} = &parsed{{ .Name }}
			{{- else }}
			query.{{ .Name }} = parsed{{ .Name }}
			{{- end }}
		}
		{{- else if eq .ParseKind "bool" }}
		if parsed{{ .Name }}, err := strconv.ParseBool(value{{ .Name }}); err != nil {
			WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid query param: {{ .JSONName }}"})
			return
		} else {
			{{- if .IsPointer }}
			query.{{ .Name }} = &parsed{{ .Name }}
			{{- else }}
			query.{{ .Name }} = parsed{{ .Name }}
			{{- end }}
		}
		{{- else }}
		{{- if .IsPointer }}
		query.{{ .Name }} = &value{{ .Name }}
		{{- else }}
		query.{{ .Name }} = value{{ .Name }}
		{{- end }}
		{{- end }}
		{{- else }}
		if value{{ .Name }} := values.Get({{ printf "%q" .JSONName }}); value{{ .Name }} != "" {
			{{- if eq .ParseKind "int64" }}
			if parsed{{ .Name }}, err := strconv.ParseInt(value{{ .Name }}, 10, 64); err != nil {
				WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid query param: {{ .JSONName }}"})
				return
			} else {
				{{- if .IsPointer }}
				query.{{ .Name }} = &parsed{{ .Name }}
				{{- else }}
				query.{{ .Name }} = parsed{{ .Name }}
				{{- end }}
			}
			{{- else if eq .ParseKind "float64" }}
			if parsed{{ .Name }}, err := strconv.ParseFloat(value{{ .Name }}, 64); err != nil {
				WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid query param: {{ .JSONName }}"})
				return
			} else {
				{{- if .IsPointer }}
				query.{{ .Name }} = &parsed{{ .Name }}
				{{- else }}
				query.{{ .Name }} = parsed{{ .Name }}
				{{- end }}
			}
			{{- else if eq .ParseKind "bool" }}
			if parsed{{ .Name }}, err := strconv.ParseBool(value{{ .Name }}); err != nil {
				WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid query param: {{ .JSONName }}"})
				return
			} else {
				{{- if .IsPointer }}
				query.{{ .Name }} = &parsed{{ .Name }}
				{{- else }}
				query.{{ .Name }} = parsed{{ .Name }}
				{{- end }}
			}
			{{- else }}
			{{- if .IsPointer }}
			query.{{ .Name }} = &value{{ .Name }}
			{{- else }}
			query.{{ .Name }} = value{{ .Name }}
			{{- end }}
			{{- end }}
		}
		{{- end }}
		{{- end }}
		{{- end }}

		{{- if .HasBody }}
		var body {{ .BodyType }}
		if err := ReadJSON(r, &body); err != nil {
			WriteError(w, &RPCError{Status: http.StatusBadRequest, Message: "invalid json", Data: err.Error()})
			return
		}
		{{- end }}

		resp, err := svc.{{ goMethodName .Name }}(ctx{{ if .HasPath }}, path{{ end }}{{ if .HasQuery }}, &query{{ end }}{{ if .HasBody }}, body{{ end }})
		if err != nil {
			WriteError(w, err)
			return
		}
		WriteJSON(w, http.StatusOK, resp)
	}
}

{{- end }}
{{- end }}
