// Code generated by openapi-rpc-codegen (go-server). DO NOT EDIT.

package {{ .Package }}

import (
	"encoding/json"
	"net/http"
)

type RPCError struct {
	Status int         `json:"-"`
	Message string     `json:"message"`
	Data    any        `json:"data,omitempty"`
}

func (e *RPCError) Error() string { return e.Message }

func WriteJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func ReadJSON(r *http.Request, v any) error {
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	return dec.Decode(v)
}

func WriteError(w http.ResponseWriter, err error) {
	if re, ok := err.(*RPCError); ok {
		WriteJSON(w, re.Status, re)
		return
	}
	// default: 500
	WriteJSON(w, http.StatusInternalServerError, &RPCError{
		Status: http.StatusInternalServerError,
		Message: "internal error",
	})
}
