// Code generated by openapi-rpc-codegen (go-server). DO NOT EDIT.

package {{ .Package }}

{{- if .Types }}

{{- range .Types }}
{{- if eq .Kind "struct" }}

type {{ .Name }} struct {
{{- range .StructFields }}
	{{ .Name }} {{ .Type }} {{ .Tag }}
{{- end }}
}

{{- else if eq .Kind "enum" }}

type {{ .Name }} string

const (
{{- range .EnumValues }}
	{{ $.Package }}{{/* no-op: keep scope */}}
	{{- /* const name = Type + "_" + value */ -}}
	{{- $v := . -}}
	{{- /* sanitize const name roughly */ -}}
	{{- /* template funcs do this better; we keep simple */ -}}
	{{- /* const value */ -}}
	{{- /* We'll fill const name via func */ -}}
{{- end }}
)

{{- else if eq .Kind "alias" }}

type {{ .Name }} = {{ .Alias }}

{{- end }}

{{- end }}
{{- end }}
