/* AUTO-GENERATED FILE - DO NOT EDIT.
 * Generated by openapi-rpc-codegen (ts-wx).
 */

{{- range .Types }}
{{- if eq .Kind "object" }}
export interface {{ .Name }} {
{{- range .Fields }}
  {{- if isSafeProp .Name }}{{ .Name }}{{ else }}"{{ .Name }}"{{ end }}{{ if .Optional }}?{{ end }}: {{ .Type }};
{{- end }}
}
{{- if .Nullable }}
export type {{ .Name }}Nullable = {{ .Name }} | null;
{{- end }}

{{- else if eq .Kind "enum" }}
export type {{ .Name }} = {{ enumUnion .Enum }}{{ if .Nullable }} | null{{ end }};

{{- else if eq .Kind "alias" }}
export type {{ .Name }} = {{ .Alias }};

{{- end }}
{{- end }}
