/* AUTO-GENERATED FILE - DO NOT EDIT.
 * Generated by openapi-rpc-codegen (ts-wx).
 */

export class RpcError extends Error {
  public readonly httpStatus: number;
  public readonly data: unknown;
  constructor(message: string, httpStatus: number, data: unknown) {
    super(message);
    this.name = "RpcError";
    this.httpStatus = httpStatus;
    this.data = data;
  }
}

type RequestOptions = {
  query?: Record<string, any>;
  body?: any;
  headers?: Record<string, string>;
};

export async function rpcRequest<T>(
  baseURL: string,
  method: "GET" | "POST",
  path: string,
  options: RequestOptions,
): Promise<T> {
  const url = joinURL(baseURL, path) + buildQuery(options.query);
  const header: Record<string, string> = {
    "Content-Type": "application/json",
    ...(options.headers ?? {}),
  };

  return new Promise<T>((resolve, reject) => {
    wx.request({
      url,
      method,
      header,
      data: method === "POST" ? (options.body ?? null) : undefined,
      success(res) {
        const status = (res.statusCode ?? 0) as number;
        const data = (res as any).data;
        if (status >= 200 && status < 300) {
          resolve(data as T);
          return;
        }
        reject(new RpcError(`HTTP ${status}`, status, data));
      },
      fail(err) {
        reject(new RpcError((err as any)?.errMsg ?? "network error", 0, err));
      },
    });
  });
}

function joinURL(baseURL: string, path: string): string {
  const a = baseURL.endsWith("/") ? baseURL.slice(0, -1) : baseURL;
  const b = path.startsWith("/") ? path : "/" + path;
  return a + b;
}

// Arrays are serialized as repeat: a=1&a=2
function buildQuery(query?: Record<string, any>): string {
  if (!query) return "";
  const parts: string[] = [];
  for (const k of Object.keys(query)) {
    const v = (query as any)[k];
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      for (const x of v) {
        if (x === undefined || x === null) continue;
        parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(x))}`);
      }
    } else {
      parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);
    }
  }
  return parts.length ? `?${parts.join("&")}` : "";
}
